"""Whisper Wayland - Constants

Defines application-wide constants for audio configuration,
API settings, and system integration parameters.
"""


class Constants:
    """Static class containing all application constants."""

    # Audio Configuration
    DEFAULT_SAMPLE_RATE = 16000
    HIGH_QUALITY_SAMPLE_RATE = 44100
    DEFAULT_CHUNK_SIZE = 1024
    LARGE_CHUNK_SIZE = 2048
    DEFAULT_RECORDING_DURATION = 30
    LONG_RECORDING_DURATION = 60
    DEFAULT_MIC_CHECK_DURATION = 1.0
    DEFAULT_MANUAL_MIC_CHECK_DURATION = 5.0
    DEAD_MIC_DBFS_THRESHOLD = -70.0
    QUIET_MIC_DBFS_THRESHOLD = -55.0
    NOISY_MIC_DBFS_THRESHOLD = -20.0
    CLIPPING_SAMPLE_THRESHOLD = 32700
    CLIPPING_RATE_WARNING_THRESHOLD = 1.0

    # Text Processing
    DEFAULT_TEXT_INSERTION_DELAY = 0.1
    CUSTOM_TEXT_INSERTION_DELAY = 0.5
    TEXT_PREVIEW_LENGTH = 50
    TRANSCRIPTION_PREVIEW_LENGTH = 100

    # System Limits
    WAV_HEADER_SIZE = 44
    MAX_FUNCTION_ARGUMENTS = 5

    # Test Constants
    EXPECTED_DEVICE_COUNT = 2
    EXPECTED_CHANNELS_MONO = 1
    EXPECTED_CHANNELS_STEREO = 2
    EXPECTED_HANDLER_COUNT = 2
    MIN_LOGGER_CALLS = 3
